apiVersion: v1
kind: Template
metadata:
  name: kubernetes-collector
  annotations:
    pluginVersion: "alpha"
    meterVersion: ">=0.11"
    displayName: "Kubernetes Collector"
    description: "Kubernetes Collector"
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: 6fusion-kubernetes-collector
- apiVersion: v1
  kind: Service
  metadata:
    name: k8scollector-master
    namespace: 6fusion-kubernetes-collector
    labels:
      6fusion-app: k8scollector-master
  spec:
    ports:
    - port: 27017
      protocol: TCP
      name: k8scollector-master-mongodb
    selector:
      6fusion-app: k8scollector-master
    type: NodePort
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: 6fusion-k8scollector-master
    namespace: 6fusion-kubernetes-collector
    labels:
      6fusion-app: k8scollector-master
  spec:
    replicas: 1
    selector:
      6fusion-app: k8scollector-master
    template:
      metadata:
        name: 6fusion-k8scollector-master
        labels:
          6fusion-app: k8scollector-master
      spec:
        containers:
        - name: k8scollector-inventory
          image: 6fusion/k8collector-inventory:alpha
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: kube-secret
            mountPath: /var/run/secrets/k8scollector/kube
          - name: on-prem-secret
            mountPath: /var/run/secrets/k8scollector/on-premise
        - name: k8scollector-onpremise
          image: 6fusion/k8collector-onpremise:alpha
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: kube-secret
            mountPath: /var/run/secrets/k8scollector/kube
          - name: on-prem-secret
            mountPath: /var/run/secrets/k8scollector/on-premise
        - name: k8scollector-cleancache
          image: 6fusion/k8collector-cleancache:alpha
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: kube-secret
            mountPath: /var/run/secrets/k8scollector/kube
          - name: on-prem-secret
            mountPath: /var/run/secrets/k8scollector/on-premise
        - name: k8scollector-mongodb
          image: mongo:3.2
          volumeMounts:
          - mountPath: /data/db
            name: "k8scollector-mongodb"
        volumes:
        - name: kube-secret
          secret:
            secretName: kube-secret
        - name: on-prem-secret
          secret:
            secretName: on-premise-secret
        - name: "k8scollector-mongodb"
          hostPath:
            path: "/var/lib/k8scollector/data/db"
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: 6fusion-k8scollector-metrics
    namespace: 6fusion-kubernetes-collector
    labels:
      6fusion-app: k8scollector-metrics
  spec:
    replicas: 2  # Set the amount of metrics collectors replicas (default 2)
    selector:
      6fusion-app: k8scollector-metrics
    template:
      metadata:
        name: 6fusion-k8scollector-metrics
        labels:
          6fusion-app: k8scollector-metrics
      spec:
        containers:
        - name: k8scollector-metrics
          image: 6fusion/k8collector-metrics:alpha
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: kube-secret
            mountPath: /var/run/secrets/k8scollector/kube
          - name: on-prem-secret
            mountPath: /var/run/secrets/k8scollector/on-premise
        volumes:
        - name: kube-secret
          secret:
            secretName: kube-secret
        - name: on-prem-secret
          secret:
            secretName: on-premise-secret
        imagePullSecrets:
        - name: registry-pull-secret
parameters:
# Kubernetes config
- description: "Host or IP address Kubernetes API server"
  section: kube
  sectionDisplayName: Kubernetes
  name: kube-host
  displayName: "Kubernetes Host"
  expandExpression: ${KUBERNETES_PRIVATE_HOST}
- name: kube-port
  section: kube
  sectionDisplayName: Kubernetes
  displayName: "Kubernetes Port"
  type: int
  description: "Port of Kubernetes API server"
  expandExpression: ${KUBERNETES_PRIVATE_PORT}
- name: kube-token
  description: "Token of the Kubernetes API server (specify only for a remote Kube API Server)"
  section: kube
  sectionDisplayName: Kubernetes
  displayName: "token"
- name: kube-use-ssl
  section: kube
  sectionDisplayName: Kubernetes
  description: "Access the Kubernetes API via SSL"
  displayName: "Use SSL?"
  type: boolean
  value: "true"
- name: kube-verify-ssl
  section: kube
  sectionDisplayName: Kubernetes
  description: "Verify SSL certificate. Do not enable if using self-signed certificates"
  displayName: "Verify SSL certificate?"
  type: boolean
  value: "false"
- name: cadvisor-host
  section: kube
  sectionDisplayName: Kubernetes
  description: "Address of the cluster master cAdvisor host"
  displayName: "cAdvisor Host"
- name: cadvisor-port
  section: kube
  sectionDisplayName: Kubernetes
  type: int
  displayName: "cAdvisor Port"
  value: "4194"
# On-Prem config
- name: host
  displayName: Host
  section: on-premise
  sectionDisplayName: "Meter API"
  description: "Address of the 6fusion On-Prem Meter"
  expandExpression: ${METER_API_HOST}
- name: port
  displayName: Port
  section: on-premise 
  sectionDisplayName: "Meter API"
  description: "Port of the 6fusion Meter. Typically 80 for unecrypted access; 443 for SSL"
  expandExpression: ${METER_API_SSL_PORT}
- name: token
  displayName: "6fusion Meter API token"
  section: on-premise
  sectionDisplayName: "Meter API"
  description: "OAuth token to use to access the 6fusion Meter. Not required if OAuth is not enabled on the meter."
- name: use-ssl
  displayName: "Use SSL?"
  section: on-premise
  sectionDisplayName: "Meter API"
  description: "Use SSL for all interaction with the 6fusion Meter"
  value: "true"
  type: boolean
- name: verify-ssl
  displayName: "Verify SSL?"
  sectionDisplayName: "Meter API"
  section: on-premise
  description: "Verify 6fusion Meter SSL certificate. Do not enable if using self-signed certificates."
  value: "false"
  type: boolean
- name: data-age-period
  displayName: "Data Age Period"
  sectionDisplayName: "Meter API"
  section: on-premise
  description: "Age period of data for clean cache. Must be in minutes."
  value: 60
- name: organization-id
  displayName: "Organization ID"
  sectionDisplayName: "Meter API"
  section: on-premise
  description: "ID of Organization object in the 6fusion Meter"
  expandExpression: ${ORGANIZATION_ID}
- name: default-disk-io
  sectionDisplayName: "Meter API"
  section: on-premise
  type: int
  displayName: "Default Disk I/O"
  description: "The value to use for Disk I/O if the collector cannot determine the actual disk I/O speed"
  value: "10000000000"
  advanced: true
- name: default-lan-io
  sectionDisplayName: "Meter API"
  section: on-premise
  type: int
  displayName: "Default LAN I/O"
  description: "The value to use for LAN I/O if the collector cannot determine the actual LAN I/O speed"
  value: "10000000000"
  advanced: true
- name: default-wan-io
  sectionDisplayName: "Meter API"
  section: on-premise
  type: int
  displayName: "Default WAN I/O"
  description: "The value to use for WAN I/O if the collector cannot determine the actual WAN I/O speed"
  advanced: true
  value: "100000000"
